import { ReduxProvider } from "@/redux/provider";
import "./globals.css";
import VerifyUser from "@/components/Global/VerifyUser";

export const metadata = {
  title: "Summarist",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <VerifyUser />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
